package main

import (
	"net"
	"bufio"
	"os"
	"fmt"
	"strconv"
)

// A "Sender" is capable of sending out messages that are generated by the user
type Sender struct {
	UserName string // The username of the sender
	IPAddress net.IP // The IP address of the sender
	Port int // The port being used by the sender
}

// Will cause the Sender to start and do its thing
func (s Sender) Run() {

	scanner := bufio.NewScanner(os.Stdin)
	for scanner.Scan() {
		messageContents := scanner.Text()

		s.buildMessage(messageContents)
		s.sendMessage(messageContents) // TODO make this take the generated message as an argument
	}
}

// Constructs a message using the provided String as the contents of the message
func (s Sender) buildMessage(messageContents string) {
	// TODO actually build the message
	fmt.Println(messageContents)
}

// Sends the message out
func (s Sender) sendMessage(contents string) {
	// TODO implement
	// Send via UDP to the IP and Port
	broadcastAddr, err := net.ResolveUDPAddr("udp", s.IPAddress.String() + ":" + strconv.Itoa(s.Port))

	if err != nil {
		fmt.Errorf("Could not broadcast: %v", err)
	}

	udpSocket, err := net.Dial("udp", broadcastAddr.String())

	if err != nil {
		fmt.Errorf("Could not use the UDP socket: %v", err)
	}

	udpSocket.Write([]byte(contents))
}
